// <auto-generated />
using AlbumApp.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AlbumApp.Migrations
{
    [DbContext(typeof(AlbumsDbContext))]
    [Migration("20250219015344_SeedMoreAlbums")]
    partial class SeedMoreAlbums
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AlbumApp.Entities.Album", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(3,1)");

                    b.Property<string>("Songs")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Albums");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Artist = "Burna Boy",
                            Rating = 9.6m,
                            Songs = "Dangote, Anybody, Gbona",
                            Title = "African Giant"
                        },
                        new
                        {
                            Id = 2,
                            Artist = "Olamide",
                            Rating = 8.8m,
                            Songs = "Loading, Infinity, Triumphant",
                            Title = "Carpe Diem"
                        },
                        new
                        {
                            Id = 3,
                            Artist = "Kizz Daniel",
                            Rating = 9.1m,
                            Songs = "One Ticket, Madu, Bad",
                            Title = "No Bad Songz"
                        },
                        new
                        {
                            Id = 4,
                            Artist = "Fireboy DML",
                            Rating = 8.7m,
                            Songs = "Champion, Tattoo, Remember Me",
                            Title = "Apollo"
                        },
                        new
                        {
                            Id = 5,
                            Artist = "Olamide",
                            Rating = 8.8m,
                            Songs = "Loading, Infinity, Triumphant",
                            Title = "Carpe Diem"
                        },
                        new
                        {
                            Id = 6,
                            Artist = "Kizz Daniel",
                            Rating = 9.1m,
                            Songs = "One Ticket, Madu, Bad",
                            Title = "No Bad Songz"
                        },
                        new
                        {
                            Id = 7,
                            Artist = "Fireboy DML",
                            Rating = 8.7m,
                            Songs = "Champion, Tattoo, Remember Me",
                            Title = "Apollo"
                        },
                        new
                        {
                            Id = 8,
                            Artist = "Adekunle Gold",
                            Rating = 8.9m,
                            Songs = "Something Different, Pretty Girl",
                            Title = "Afro Pop Vol. 1"
                        },
                        new
                        {
                            Id = 9,
                            Artist = "Rema",
                            Rating = 9.2m,
                            Songs = "Soundgasm, Calm Down, FYN",
                            Title = "Rave & Roses"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
